name: Bazel Build & Test

on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - '**'
    types: [opened, synchronize, reopened]
  merge_group:
    branches:
      - main

jobs:
  bazel-build:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    container: ros:jazzy

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache APT packages
        uses: actions/cache@v3
        with:
          path: /var/cache/apt
          key: ${{ runner.os }}-apt-${{ hashFiles('dependencies.txt') }}
          restore-keys: |
            ${{ runner.os }}-apt-

      - name: Install Base Dependencies
        run: |
          sudo apt-get update && sudo apt-get upgrade -y
          sudo apt-get update && apt-get install -y --no-install-recommends \
          curl gnupg2 lsb-release software-properties-common \
          locales \
          git \
          wget

      - name: Install Project Dependencies
        run: |
          sudo apt-get install -y --no-install-recommends $(cat dependencies.txt)

      - name: Install Bazel (Bazelisk)
        run: |
          wget https://github.com/bazelbuild/bazelisk/releases/download/v1.19.0/bazelisk-linux-amd64
          chmod +x bazelisk-linux-amd64
          sudo mv bazelisk-linux-amd64 /usr/local/bin/bazel

      - name: Build All Targets
        run: |
          bazel build //motorium/...

      - name: Run Tests
        run: |
          bazel test //motorium/...